// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;

namespace Detection
{
    public partial class DetectionMachineLearning
    {
        /// <summary>
        /// model input class for DetectionMachineLearning.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"-1")]
            public float __1 { get; set; }

            [ColumnName(@"-1_2")]
            public float __1_2 { get; set; }

            [ColumnName(@"-1_3")]
            public float __1_3 { get; set; }

            [ColumnName(@"-1_4")]
            public float __1_4 { get; set; }

            [ColumnName(@"-1_5")]
            public float __1_5 { get; set; }

            [ColumnName(@"-1_6")]
            public float __1_6 { get; set; }

            [ColumnName(@"-1_7")]
            public float __1_7 { get; set; }

            [ColumnName(@"-1_8")]
            public float __1_8 { get; set; }

            [ColumnName(@"-1_9")]
            public float __1_9 { get; set; }

            [ColumnName(@"-1_10")]
            public float __1_10 { get; set; }

            [ColumnName(@"-1_11")]
            public float __1_11 { get; set; }

            [ColumnName(@"-1_12")]
            public float __1_12 { get; set; }

            [ColumnName(@"-1_13")]
            public float __1_13 { get; set; }

            [ColumnName(@"-1_14")]
            public float __1_14 { get; set; }

            [ColumnName(@"-1_15")]
            public float __1_15 { get; set; }

            [ColumnName(@"-1_16")]
            public float __1_16 { get; set; }

            [ColumnName(@"-1_17")]
            public float __1_17 { get; set; }

            [ColumnName(@"-1_18")]
            public float __1_18 { get; set; }

            [ColumnName(@"-1_19")]
            public float __1_19 { get; set; }

            [ColumnName(@"-1_20")]
            public float __1_20 { get; set; }

            [ColumnName(@"-1_21")]
            public float __1_21 { get; set; }

            [ColumnName(@"-1_22")]
            public float __1_22 { get; set; }

            [ColumnName(@"-1_23")]
            public float __1_23 { get; set; }

            [ColumnName(@"-1_24")]
            public float __1_24 { get; set; }

            [ColumnName(@"-1_25")]
            public float __1_25 { get; set; }

            [ColumnName(@"-1_26")]
            public float __1_26 { get; set; }

            [ColumnName(@"-1_27")]
            public float __1_27 { get; set; }

            [ColumnName(@"-1_28")]
            public float __1_28 { get; set; }

            [ColumnName(@"-1_29")]
            public float __1_29 { get; set; }

            [ColumnName(@"-1_30")]
            public float __1_30 { get; set; }

            [ColumnName(@"-1_31")]
            public float __1_31 { get; set; }

            [ColumnName(@"-1_32")]
            public float __1_32 { get; set; }

            [ColumnName(@"-1_33")]
            public float __1_33 { get; set; }

            [ColumnName(@"-1_34")]
            public float __1_34 { get; set; }

            [ColumnName(@"-1_35")]
            public float __1_35 { get; set; }

            [ColumnName(@"-1_36")]
            public float __1_36 { get; set; }

            [ColumnName(@"-1_37")]
            public float __1_37 { get; set; }

            [ColumnName(@"-1_38")]
            public float __1_38 { get; set; }

            [ColumnName(@"-1_39")]
            public float __1_39 { get; set; }

            [ColumnName(@"-1_40")]
            public float __1_40 { get; set; }

            [ColumnName(@"-1_41")]
            public float __1_41 { get; set; }

            [ColumnName(@"-1_42")]
            public float __1_42 { get; set; }

            [ColumnName(@"-1_43")]
            public float __1_43 { get; set; }

            [ColumnName(@"-1_44")]
            public float __1_44 { get; set; }

            [ColumnName(@"-1_45")]
            public float __1_45 { get; set; }

            [ColumnName(@"-1_46")]
            public float __1_46 { get; set; }

            [ColumnName(@"-1_47")]
            public float __1_47 { get; set; }

            [ColumnName(@"-1_48")]
            public float __1_48 { get; set; }

            [ColumnName(@"-1_49")]
            public float __1_49 { get; set; }

            [ColumnName(@"-1_50")]
            public float __1_50 { get; set; }

            [ColumnName(@"-1_51")]
            public float __1_51 { get; set; }

            [ColumnName(@"-1_52")]
            public float __1_52 { get; set; }

            [ColumnName(@"-1_53")]
            public float __1_53 { get; set; }

            [ColumnName(@"-1_54")]
            public float __1_54 { get; set; }

            [ColumnName(@"-1_55")]
            public float __1_55 { get; set; }

            [ColumnName(@"-1_56")]
            public float __1_56 { get; set; }

            [ColumnName(@"-1_57")]
            public float __1_57 { get; set; }

            [ColumnName(@"-1_58")]
            public float __1_58 { get; set; }

            [ColumnName(@"-1_59")]
            public float __1_59 { get; set; }

            [ColumnName(@"-1_60")]
            public float __1_60 { get; set; }

            [ColumnName(@"-1_61")]
            public float __1_61 { get; set; }

            [ColumnName(@"-1_62")]
            public float __1_62 { get; set; }

            [ColumnName(@"-1_63")]
            public float __1_63 { get; set; }

            [ColumnName(@"-1_64")]
            public float __1_64 { get; set; }

            [ColumnName(@"-1_65")]
            public float __1_65 { get; set; }

            [ColumnName(@"-1_66")]
            public float __1_66 { get; set; }

            [ColumnName(@"-1_67")]
            public float __1_67 { get; set; }

            [ColumnName(@"-1_68")]
            public float __1_68 { get; set; }

            [ColumnName(@"-1_69")]
            public float __1_69 { get; set; }

            [ColumnName(@"-1_70")]
            public float __1_70 { get; set; }

            [ColumnName(@"-1_71")]
            public float __1_71 { get; set; }

            [ColumnName(@"-1_72")]
            public float __1_72 { get; set; }

            [ColumnName(@"-1_73")]
            public float __1_73 { get; set; }

            [ColumnName(@"-1_74")]
            public float __1_74 { get; set; }

            [ColumnName(@"-1_75")]
            public float __1_75 { get; set; }

            [ColumnName(@"-1_76")]
            public float __1_76 { get; set; }

            [ColumnName(@"-1_77")]
            public float __1_77 { get; set; }

            [ColumnName(@"-1_78")]
            public float __1_78 { get; set; }

            [ColumnName(@"-1_79")]
            public float __1_79 { get; set; }

            [ColumnName(@"-1_80")]
            public float __1_80 { get; set; }

            [ColumnName(@"-1_81")]
            public float __1_81 { get; set; }

            [ColumnName(@"-1_82")]
            public float __1_82 { get; set; }

            [ColumnName(@"-1_83")]
            public float __1_83 { get; set; }

            [ColumnName(@"-1_84")]
            public float __1_84 { get; set; }

            [ColumnName(@"-1_85")]
            public float __1_85 { get; set; }

            [ColumnName(@"-1_86")]
            public float __1_86 { get; set; }

            [ColumnName(@"-1_87")]
            public float __1_87 { get; set; }

            [ColumnName(@"-1_88")]
            public float __1_88 { get; set; }

            [ColumnName(@"-1_89")]
            public float __1_89 { get; set; }

            [ColumnName(@"-1_90")]
            public float __1_90 { get; set; }

            [ColumnName(@"-1_91")]
            public float __1_91 { get; set; }

            [ColumnName(@"-1_92")]
            public float __1_92 { get; set; }

            [ColumnName(@"-1_93")]
            public float __1_93 { get; set; }

            [ColumnName(@"-1_94")]
            public float __1_94 { get; set; }

            [ColumnName(@"-1_95")]
            public float __1_95 { get; set; }

            [ColumnName(@"-1_96")]
            public float __1_96 { get; set; }

            [ColumnName(@"-1_97")]
            public float __1_97 { get; set; }

            [ColumnName(@"-1_98")]
            public float __1_98 { get; set; }

            [ColumnName(@"-1_99")]
            public float __1_99 { get; set; }

            [ColumnName(@"-1_100")]
            public float __1_100 { get; set; }

            [ColumnName(@"-1_101")]
            public float __1_101 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DetectionMachineLearning.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DetectionMachineLearning.zip");

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
